error_code_matcher {
  ignore_server_error_reason: SERVER_ERROR_REASON_UNKNOWN
  ignore_server_error_reason: SERVER_UNEXPECTED_EXCEPTION
  ignore_storage_error_reason: STORAGE_ERROR_REASON_UNKNOWN
  output_column_name: "ERROR_CODE"
}
clusterer {
  tokenizer {
    preprocessor {
      ignore_line_regex_matcher: "Suppressed"
      ignore_line_regex_matcher: "com.google.apps.framework"
      ignore_line_regex_matcher: "com.google.moneta.api2.framework"
      ignore_line_regex_matcher: "com.google.common.util"
      ignore_line_regex_matcher: "java.util"
      ignore_line_regex_matcher: "java.lang"
      ignore_line_regex_matcher: "\$"
      ignore_line_regex_matcher: "sun.reflect"
    }
    mode: COMBINED
    token_min_length: 1
    # Splitting on = could be useful for tokens like error_code=ERROR_CODE
    split_on: "="
    # Splitting on [ could be useful for tokens like state[RENEWAL_STOPPED]
    split_on: "\["
    split_on: "\]"
    punctuation: ":"
    punctuation: "\n"
    punctuation: "/"
    punctuation: "\t"
  }
  mini_batch: false
  min_cluster: 2
  max_cluster: 20
  output_column_name: "CLUSTER_CODE"
}
informative_column: "exception"
informative_column: "remoteException"
informative_column: "errorMessage"
summarizer {
  n_messages: 20
  summary_input_column: "exception"
  ignore_class_line_regex_matcher: "com.google.apps.framework"
  ignore_class_line_regex_matcher: "com.google.moneta.api2.framework"
  ignore_class_line_regex_matcher: "com.google.common.util"
  ignore_class_line_regex_matcher: "java.util"
  ignore_class_line_regex_matcher: "java.lang"
  ignore_class_line_regex_matcher: "\$"
  ignore_class_line_regex_matcher: "sun.reflect"
  n_class_lines_to_show: 20
}
