error_code_matcher {
  error_code: "SERVER_INTERRUPTED"
  error_code: "SERVER_PERSISTENCE_ERROR"
  error_code: "SERVER_ERROR_SET_IN_RESPONSE_BY_ACTION"
  error_code: "SERVER_ERROR_NOT_SEEDED_GUICE_EXCEPTION"
  error_code: "SERVER_NOT_A_TRANSACTION_ACTION_EXCEPTION"
  error_code: "SERVER_MESSAGE_INSTANTIATION_EXCEPTION"
  error_code: "SERVER_NOT_IMPLEMENTED_EXCEPTION"
  error_code: "SERVER_EXPERIMENT_DIVERSION_FAILURE"
  error_code: "SERVER_EXPERIMENT_OVERRIDE_FAILURE"
  error_code: "SERVER_REMOTE_FRAMEWORK_ERROR"
  error_code: "SERVER_TIMEOUT_ERROR"
  error_code: "SERVER_RESPONSE_CAN_NOT_BE_THE_DEFAULT_INSTANCE"
  error_code: "SERVER_INVALID_AUTH_CONTEXT"
  error_code: "STORAGE_LIFECYCLE_CHANGE_NOT_ALLOWED"
  error_code: "STORAGE_INVALID_STATE"
  error_code: "STORAGE_UNIT_OF_WORK_NOT_SEEDED"
  error_code: "STORAGE_STATS_COLLECTION_FAILED"
  error_code: "STORAGE_DEADLINE_EXCEEDED"
  error_code: "STORAGE_SETTING_F1_SNAPSHOT_TIMESTAMP_IS_DISALLOWED"
  error_code: "STORAGE_PAGINATED_DISALLOWED_IN_CHILD_REQUEST"
  error_code: "STORAGE_STALE_LOCK_TIMESTAMP"
  error_code: "STORAGE_DATA_CONSTRAINT_VIOLATION"
  error_code: "STORAGE_LEGACY_ENTITY_NOT_FOUND"
  error_code: "STORAGE_BATCH_READ_WRITE_MIX_NOT_ALLOWED"
  error_code: "STORAGE_BATCH_INCONSISTENT_CHILD_PAGINATION_TIMESTAMPS"
  error_code: "STORAGE_BATCH_PARENT_UNIT_OF_WORK_INVALID"
  error_code: "STORAGE_PAGINATED_DISALLOWED_WITHOUT_SNAPSHOT_TIMESTAMP"
  error_code: "RPC.CANCELLED"
  error_code: "RPC.UNKNOWN"
  error_code: "RPC.INVALID_ARGUMENT"
  error_code: "RPC.DEADLINE_EXCEEDED"
  error_code: "RPC.NOT_FOUND"
  error_code: "RPC.ALREADY_EXISTS"
  error_code: "RPC.PERMISSION_DENIED"
  error_code: "RPC.UNAUTHENTICATED"
  error_code: "RPC.RESOURCE_EXHAUSTED"
  error_code: "RPC.FAILED_PRECONDITION"
  error_code: "RPC.ABORTED"
  error_code: "RPC.OUT_OF_RANGE"
  error_code: "RPC.UNIMPLEMENTED"
  error_code: "RPC.INTERNAL"
  error_code: "RPC.UNAVAILABLE"
  error_code: "RPC.DATA_LOSS"
}
clusterer {
  tokenizer {
    preprocessor {
      ignore_line_regex_matcher: "\tat"
      ignore_line_regex_matcher: "Suppressed"
      search_line_regex_matcher: ":"
    }
    mode: HUMAN_READABLE
    token_min_length: 1
    split_on: "="
  }
  mini_batch: false
  min_cluster: 2
  max_cluster: 20
}
