error_code_matcher {
  ignore_server_error_reason: SERVER_ERROR_REASON_UNKNOWN
  ignore_server_error_reason: SERVER_UNEXPECTED_EXCEPTION
  ignore_storage_error_reason: STORAGE_ERROR_REASON_UNKNOWN
  output_column_name: "ErrorCode"
}
clusterer {
  tokenizer {
    preprocessor {
      ignore_line_regex_matcher: "Suppressed"
    }
    mode: HUMAN_READABLE
    token_min_length: 1
    # Splitting on = could be useful for tokens like error_code=ERROR_CODE
    split_on: "="
    # Splitting on [ could be useful for tokens like state[RENEWAL_STOPPED]
    split_on: "\["
    split_on: "\]"
    punctuation: ":"
    punctuation: "\n"
    punctuation: "/"
    punctuation: "\t"
    ignore_token_matcher: "eye3-ignored"
  }
  mini_batch: false
  min_cluster: 2
  max_cluster: 20
  output_column_name: "ClusterCode"
}
informative_column: "exception"
informative_column: "remoteException"
informative_column: "errorMessage"
summarizer {
  n_messages: 20
  n_class_lines_to_show: 20
}
