error_code_matcher {
  ignore_server_error_reason: SERVER_ERROR_REASON_UNKNOWN
  ignore_server_error_reason: SERVER_UNEXPECTED_EXCEPTION
  ignore_storage_error_reason: STORAGE_ERROR_REASON_UNKNOWN
  output_column_name: "ErrorCode"
}
clusterer {
  tokenizer {
    preprocessor {
      ignore_line_regex_matcher: "com.google.apps.framework.request.impl"
      ignore_line_regex_matcher: "com.google.net.rpc3.impl"
      ignore_line_regex_matcher: "com.google.moneta.api2.framework"
      ignore_line_regex_matcher: "com.google.common.util"
      ignore_line_regex_matcher: "com.google.common.context"
      ignore_line_regex_matcher: "com.google.tracing"
      ignore_line_regex_matcher: "java.util"
      ignore_line_regex_matcher: "\$"
      ignore_line_regex_matcher: "sun.reflect"
    }
    mode: STACK_TRACE_LINES
    token_min_length: 1
    split_on: "="
  }
  mini_batch: false
  min_cluster: 2
  max_cluster: 20
  output_column_name: "ClusterCode"
}
informative_column: "exception"
informative_column: "remoteException"
informative_column: "errorMessage"
summarizer {
  n_messages: 20
  n_class_lines_to_show: 20
}
